// Cloudflare-safe provenance checks: Node only; no native client, Python, or sibling repository.
import fs from 'node:fs';
import { createHash } from 'node:crypto';

const schemas = {
  Adventure: ['key', 'Level', 'Emote', 'MinTime', 'MaxTime', 'PlaceName', 'Name'],
  Emote: ['key', 'Name', 'TextCommand'],
  TextCommand: ['key', 'Command'],
  PlaceName: ['key', 'Name'],
  Level: ['key', 'X', 'Y', 'Z', 'Map'],
  Map: ['key', 'Id', 'PlaceName', 'SizeFactor', 'OffsetX', 'OffsetY'],
};
const supplements = ['tools/sources/cycleapple-arr.js', 'tools/sources/babelin.html'];
const outputs = ['data/zones.js', 'data/sightseeing-data.js'];
const root = new URL('../', import.meta.url);
/** @param {string} path */
const bytes = path => fs.readFileSync(new URL(path, root));
/** @param {Uint8Array} data */
const sha = data => createHash('sha256').update(data).digest('hex');
/** @param {string} message */
const fail = message => { throw new Error(message); };
/** @param {unknown} value @param {string[]} keys */
const exactKeys = (value, keys) => value !== null && typeof value === 'object' && !Array.isArray(value)
  && JSON.stringify(Object.keys(value).sort()) === JSON.stringify([...keys].sort());

/** @param {string} text @param {(row: string[]) => void} consume */
function csvRows(text, consume) {
  let field = '', quoted = false, closed = false;
  /** @type {string[]} */
  let row = [];
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') { quoted = false; closed = true; }
      else field += c;
    } else if (c === ',' || c === '\n') {
      row.push(field); field = ''; closed = false;
      if (c === '\n') { consume(row); row = []; }
    } else if (closed) fail('CSV contains text after a closing quote');
    else if (c === '"') {
      if (field) fail('CSV quote inside an unquoted field');
      quoted = true;
    } else field += c;
  }
  if (quoted || closed || field || row.length) fail('CSV is not terminated with a complete LF record');
}

try {
  if (process.argv.length > 2) fail('usage: node tools/validate-sources.mjs');
  const nativeBytes = bytes('tools/sources/native-manifest.json');
  const native = JSON.parse(nativeBytes.toString('utf8'));
  if (native.format !== 1 || typeof native.clientVersion !== 'string'
      || !/^\d{4}\.\d{2}\.\d{2}\.\d{4}\.\d{4}$/.test(native.clientVersion)) fail('Invalid native client version');
  if (!exactKeys(native.sheets, Object.keys(schemas))) fail('Native manifest must contain exactly six sheets');
  let namedAdventures = 0;
  for (const [name, columns] of Object.entries(schemas)) {
    const entry = native.sheets[name];
    if (entry.file !== `tc_${name}.csv`) fail(`${name}: invalid source path`);
    const data = bytes('tools/sources/' + entry.file);
    if (sha(data) !== entry.sha256) fail(`${name}: bytes SHA-256 mismatch`);
    if (data[0] === 0xef && data[1] === 0xbb && data[2] === 0xbf || data.includes(13) || data.at(-1) !== 10) {
      fail(`${name}: UTF-8 without BOM and LF required`);
    }
    const text = new TextDecoder('utf-8', { fatal: true }).decode(data);
    let count = -1;
    const ids = new Set();
    csvRows(text, row => {
      if (count === -1) {
        if (JSON.stringify(row) !== JSON.stringify(columns)) fail(`${name}: named header mismatch`);
      } else {
        if (row.length !== columns.length || !/^\d+$/.test(row[0]) || ids.has(row[0])) fail(`${name}: malformed/duplicate row`);
        ids.add(row[0]);
        if (name === 'Adventure' && row[columns.indexOf('Name')]) namedAdventures++;
      }
      count++;
    });
    if (!Number.isSafeInteger(entry.rows) || entry.rows <= 0 || count !== entry.rows) fail(`${name}: row count mismatch`);
  }
  if (namedAdventures !== 340) fail('Adventure baseline must contain 340 names');
  const generation = JSON.parse(bytes('tools/sources/generation-manifest.json').toString('utf8'));
  if (generation.format !== 1 || generation.clientVersion !== native.clientVersion
      || generation.nativeManifestSha256 !== sha(nativeBytes)) fail('Native version/snapshot changed; regenerate both outputs');
  if (!exactKeys(generation.supplements, supplements) || !exactKeys(generation.outputs, outputs)) fail('Generation manifest scope mismatch');
  for (const path of supplements) if (generation.supplements[path] !== sha(bytes(path))) fail(`${path}: supplement changed; regenerate`);
  for (const path of outputs) if (generation.outputs[path] !== sha(bytes(path))) fail(`${path}: generated bytes drift`);
  console.log(`✓ native/generation provenance: ${native.clientVersion}, 6 sheets, 340 adventures, 2 bound outputs`);
} catch (error) {
  console.error('✗ source provenance: ' + (error instanceof Error ? error.message : String(error)));
  process.exit(1);
}
